### ISSUE TITLE
Add pod diasporabr

### ISSUE THREAD

**Issue by pizzamaker** [martinchodev/Diaspora-Native-WebApp#3] opened 2015-06-22 20:13 UTC
Right now the pod https://diasporabr.com.br/ is not included in the list. Please do :)

**Comment by mdev88** [comment] 2015-06-23 13:40
Hello Pizzamaker!
The app currently uses a list of pods registered in https://podupti.me/
I have no relation with the people of podupti.me but I think it's a useful service because it tracks the uptime and gives some interesting stats about the pods so that  people interested in creating an account can choose the pod that better satisfies their needs. I recommend you (or the pod admin of diasporabr.com.br) should add that pod to the list.

Having said that, I will add the possibility to add a custom pod that is not listed because I think it's a good feature.
I will close this issue when that's done.

Thanks!

**Comment by pizzamaker** [comment] 2015-06-23 14:57
That's curious, because DiasporaBR used to be on that list...

**Comment by mdev88** [comment] 2015-06-23 15:07
I will check if I'm getting all the data correctly from there. Maybe the problem is on my end.

**Comment by mdev88** [comment] 2015-06-24 01:23
It turns out that the pod was on the list! :D

![screenshot_2015-06-23-22-16-36](https://cloud.githubusercontent.com/assets/7395872/8320888/67c44042-19f6-11e5-8e83-9c0a89599abd.png)

**Comment by mdev88** [comment] 2015-06-24 02:02
Done! In the next update you will also be able to just write the domain of the pod and use that if it's not listed.

**Closed as completed by mdev88** 2015-06-24 02:02 UTC

**Comment by pizzamaker** [comment] 2015-06-24 15:03
Great! As always thanks Martín :)

**Comment by mdev88** [comment] 2015-06-24 16:19
:+1:
