### ISSUE TITLE
Floating action button may be not well placed 

### ISSUE THREAD

**Issue by ghost** [martinchodev/Diaspora-Native-WebApp#39] opened 2015-12-14 15:52 UTC
![tmp_20453-img_20151214_164826900968768](https://cloud.githubusercontent.com/assets/3429231/11785628/033b139c-a283-11e5-9a87-46dfabc4146e.jpg)

**Comment by mdev88** [comment] 2015-12-20 18:17
This is a duplicate of issue #33

**Closed as completed by mdev88** 2015-12-20 18:17 UTC
